don't use templates

diff --git a/.github/workflows/stackhpc.yml b/.github/workflows/stackhpc.yml
--- a/.github/workflows/stackhpc.yml
+++ b/.github/workflows/stackhpc.yml
@@ -75,9 +75,11 @@ jobs:
       - name: Add bastion ssh fingerprints to known_hosts
         run: |
           cat >> ~/.ssh/known_hosts << 'EOF'
-          ${{ vars.BASTION_FINGERPRINTS }}
+          ${VARS_BASTION_FINGERPRINTS}
           EOF
         shell: bash
+        env:
+          VARS_BASTION_FINGERPRINTS: ${{ vars.BASTION_FINGERPRINTS }}
 
       - name: Ensure Ansible bastion definitions are from **current** branch
         run: |
@@ -122,7 +124,7 @@ jobs:
         run: |
           . venv/bin/activate
           . environments/.stackhpc/activate
-          ./dev/delete-cluster.py ${{ env.TF_VAR_cluster_name }} --force
+          ./dev/delete-cluster.py ${TF_VAR_CLUSTER_NAME} --force
 
       - name: Provision nodes using latest release image
         id: provision_servers
@@ -133,7 +135,7 @@ jobs:
           max_retries=3
           delay=30
           for i in $(seq 1 $max_retries); do
-            tofu apply -auto-approve -var-file="${{ env.CI_CLOUD }}.tfvars" && break
+            tofu apply -auto-approve -var-file="${CI_CLOUD}.tfvars" && break
             [ "$i" -lt "$max_retries" ] && sleep $delay || exit 1
           done
 
@@ -142,7 +144,7 @@ jobs:
           . venv/bin/activate
           . environments/.stackhpc/activate
           cd "$STACKHPC_TF_DIR"
-          tofu destroy -auto-approve -var-file="${{ env.CI_CLOUD }}.tfvars"
+          tofu destroy -auto-approve -var-file="${CI_CLOUD}.tfvars"
         if: failure() && steps.provision_servers.outcome == 'failure'
 
       - name: Configure cluster at latest release
@@ -182,7 +184,7 @@ jobs:
           max_retries=3
           delay=30
           for i in $(seq 1 $max_retries); do
-            tofu apply -auto-approve -var-file="${{ env.CI_CLOUD }}.tfvars" && break
+            tofu apply -auto-approve -var-file="${CI_CLOUD}.tfvars" && break
             [ "$i" -lt "$max_retries" ] && sleep $delay || exit 1
           done
 
@@ -273,5 +275,5 @@ jobs:
           . venv/bin/activate
           . environments/.stackhpc/activate
           cd "$STACKHPC_TF_DIR"
-          tofu destroy -auto-approve -var-file="${{ env.CI_CLOUD }}.tfvars" || echo "tofu failed in $STACKHPC_TF_DIR"
+          tofu destroy -auto-approve -var-file="${CI_CLOUD}.tfvars" || echo "tofu failed in $STACKHPC_TF_DIR"
         if: ${{ success() || cancelled() }}
